### ISSUE TITLE
Codejail mismatch: MITx+6.86x+1T2025

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#1013]
Acceptance Criteria:
- [x] Enhance darklaunch observability (if needed to diagnose this)
- [x] Fix the issue if it's real, tune alerting or scripts if it's not

The most prominent codejail dark-launch mismatches are for MITx+6.86x+1T2025 in the prod environment.

Query: `env:prod service:edx-edxapp-lms @dark_launch_emsg_match:False @course_id:"course-v1:MITx+6.86x+1T2025"`

**Comment by timmc-edx** [comment]
I sampled one of these and it looks like this is just a mismatch in the directories that show up in a stack trace. For example, this line:

```diff
-   File "/edx/app/edxapp/venvs/edxapp-sandbox/lib/python3.8/site-packages/pyparsing/util.py", line 256, in _inner
+   File "/sandbox/venv/lib/python3.8/site-packages/pyparsing/util.py", line 256, in _inner
```

We'll want to canonicalize the base dir in our comparisons.

**Comment by timmc-edx** [comment]
https://github.com/openedx/edx-platform/pull/36534 should help with this.

**Comment by timmc-edx** [comment]
I've deployed this setting to all environments and it seems to have taken care of the issue:

```
CODEJAIL_DARKLAUNCH_EMSG_NORMALIZERS:
  # Default normalizer
  - search: '/tmp/codejail-[0-9a-zA-Z]+'
    replace: '/tmp/codejail-<SANDBOX_DIR_NAME>'
  # Local and remote exec have different sandbox virtualenv directories
  - search: 'File "(/edx/app/edxapp/venvs/edxapp-sandbox|/sandbox/venv)/'
    replace: 'File "<SANDBOX_VENV>/'
```
